### ISSUE TITLE
My favourite extensions - @ewels

### ISSUE THREAD

**Issue by ewels** [nf-core/vscode-extensionpack#1]
What I can think of off the top of my head:

## Relevant extensions

* Name: markdownlint
    * Id: davidanson.vscode-markdownlint
    * Description: Markdown linting and style checking for Visual Studio Code
    * Version: 0.39.0
    * Publisher: David Anson
    * VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

* Name: Nextflow
    * Id: nextflow.nextflow
    * Description: Nextflow language support
    * Version: 0.3.0
    * Publisher: nextflow
    * VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=nextflow.nextflow

* Name: Prettier - Code formatter
    * Id: esbenp.prettier-vscode
    * Description: Code formatter using prettier
    * Version: 5.9.2
    * Publisher: Prettier
    * VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

* Name: YAML
    * Id: redhat.vscode-yaml
    * Description: YAML Language Support by Red Hat, with built-in Kubernetes syntax support
    * Version: 0.15.0
    * Publisher: Red Hat
    * VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

## Settings etc

* Auto-format on save with Black
* Line lengths set to 120 instead of 80 wherever possible

**Comment by ewels** [comment]
Added extensions in `0.1.1.`, apart from Prettier - I'm not sure that we actually use this in nf-core, might just be MultiQC that I use that for.

Not sure that we can do settings, so ignoring that bit.

**Comment by edmundmiller** [comment]
I still vote we move everything to prettier(markdown, yaml and json that is) and possibly adopt the mega-linter.

**Comment by ewels** [comment]
I didn't love the mega-linter when I had a (very brief) play with it the other day, if I'm honest. I started using Prettier for CSS and JavaScript over on MultiQC the other day though and liked it. I'd be happy to use that for Markdown / YAML here too. Is there much advantage to switching though? I mean, as far as I can tell it basically does the same thing and if it ain't broke, why fix it? 😅
