### ISSUE TITLE
Addition of Docker extension

### ISSUE THREAD

**Issue by evanfloden** [nf-core/vscode-extensionpack#11]
When developing a pipeline, the docker extension can be useful to understand which containers are available along with which are running and the container's associated metadata.

It allows users to connect to any public or private container registries. This is especially useful if you build containers locally while testing/developing pipelines, and then push those containers to an external registry when publishing the pipeline.

It also provides syntax highlighting for Dockerfiles.

The extension and more information can be found [here](https://code.visualstudio.com/docs/containers/overview).

**Comment by MatthiasZepper** [comment]
Completed and included in [Version 0.6 of the extension pack](https://marketplace.visualstudio.com/items/nf-core.nf-core-extensionpack/changelog). Thanks!
