### ISSUE TITLE
Reduce extension clutter by removing general purpose extensions that aren't specific to nextflow development.

### ISSUE THREAD

**Issue by kenibrewer** [nf-core/vscode-extensionpack#16]
I'm a big fan of this extension-pack and have adopted several of these extensions into the extensions I put in devcontainer specs for repos I own/create. However, I also think there would be value in reducing the number of extensions in this pack to those extensions that are most important to development within Nextflow or nf-core. Basically trimming down the list from the "nice-to-have" to the "must-haves". 

Here are a few specific ones I'd like to nominate for removal:

1. Gitlens

When I encourage people to install the nf-core extension pack, I've received the most pushback because the inclusion of `gitlens`. It tends to be a pretty polarizing extensions, with some people loving it and other people hating it. I also think it's worth removal because many features require a commerical subscription and the amount of visual clutter the git blames introduce. 

2. Gitignore

This extension is typically only used once when creating a repo. I would expect it to play no role whatsoever in repos created using `nf-core` tooling because those come with a gitignore.

3. Live Share

Seems like a very cool extension, but also a general purpose tool that doesn't provide specific benefit to nextflow users. 

All the other extensions seem like good additions in my view, because (like Prettier) they relate to the code quality tooling used by nf-core or ease the burden of file types that are frequently used in nextflow pipelines (like indent-rainbow).

One alternative for these `nice-to-have` extensions would be to move them to a `Recommended` extensions block for nf-core repos. (See https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions)

**Comment by mashehu** [comment]
I agree with dropping gitignore. Downgrading Gitlens and Live Share to recommended sounds like a good solution

**Comment by ewels** [comment]
Agreed - I routinely remove some of these when installing as well, it's been in the back of my mind for a while. I didn't know about `Recommneded` - agree that would be good 👍🏻

**Comment by edmundmiller** [comment]
I agree. I think those are all things that people find on their own if they want them anyways.

**Comment by kenibrewer** [comment]
Great. Three concurring voices here is enough for me to feel comfortable putting together the PR. Based on feedback to my RR [here](https://github.com/nf-core/tools/pull/2795), I'll also add the ruff extension at this time.
