### ISSUE TITLE
[Bug] Expired vscode extension marketplace personal access token

### ISSUE THREAD

**Issue by kenibrewer** [nf-core/vscode-extensionpack#19]
The personal access token used to publish our vscode extension is expired and needs to be refreshed. 

https://github.com/nf-core/vscode-extensionpack/actions/runs/8061648994

Logs Excerpt:
```
Publishing 'nf-core.nf-core-extensionpack v0.4.0'...
Error: ﻿{"$id":"1","customProperties":{"Descriptor":null,"IdentityDisplayName":null,"Token":null,"RequestedPermissions":0,"NamespaceId":"00000000-0000-0000-0000-000000000000"},"innerException":null,"message":"Access Denied: The Personal Access Token used has expired.","typeName":"Microsoft.VisualStudio.Services.Security.AccessCheckException, Microsoft.VisualStudio.Services.WebApi","typeKey":"AccessCheckException","errorCode":0,"eventId":3000}
```

**Comment by ewels** [comment]
Working on it. TLDR is that I hate Microsoft account management / auth 🤦🏻‍♂️

**Comment by kenibrewer** [comment]
@ewels Just wanted to check in about the bug. Is this something that could be addressed after the hackathon?

**Comment by ewels** [comment]
Yes! So I managed to reclaim access over the weekend! 🎉  I go @mashehu added and he was going to generate a new PAT for the repo. But then I guess he got busy.

I'll see if I can generate one now quickly and put it in..

**Comment by ewels** [comment]
ok, [done](https://github.com/nf-core/vscode-extensionpack/actions/runs/8344338753/job/22840213403)!

```
Publishing 'nf-core.nf-core-extensionpack v0.6.0'...
Extension URL (might take a few minutes): https://marketplace.visualstudio.com/items?itemName=nf-core.nf-core-extensionpack
Hub URL: https://marketplace.visualstudio.com/manage/publishers/nf-core/extensions/nf-core-extensionpack/hub
Published nf-core.nf-core-extensionpack v0.6.0.
```

**Comment by ewels** [comment]
![CleanShot 2024-03-19 at 16 11 29@2x](https://github.com/nf-core/vscode-extensionpack/assets/465550/cda798b3-bd92-42bb-a997-3d66e223136f)
