### ISSUE TITLE
@ewels - more package ideas

### ISSUE THREAD

**Issue by ewels** [nf-core/vscode-extensionpack#2]
Nice stuff from https://github.com/Functional-Genomics-Lab/functional-genomics-extension-pack/blob/main/package.json that we should probably also add:

* [codezombiech.gitignore](https://marketplace.visualstudio.com/items?itemName=codezombiech.gitignore) - `.gitignore` language support
* [EditorConfig.EditorConfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) - use `.editorconfig` files for settings if found

..probably more

**Comment by grst** [comment]
* [groovylint](https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint)

and I personally find

 * [rainbowCSV](https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv) 

very useful for editing sample sheets.

**Comment by ewels** [comment]
Great suggestions! groovylint especially looks interesting, could this finally be the solution to https://github.com/nf-core/tools/issues/430 ?

**Comment by matq007** [comment]
[code-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by apeltzer** [comment]
RainbowCSV +1, I ❤️ it !

**Comment by apeltzer** [comment]
I'm also using:

- [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) 
   For a bit more advanced git features / status logs / etc - seeing who edited which line at some point, branch view for remotes, .... tons of extra features
- [TodoTree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) 
   For nicer ToDo navigation, e.g. when going over the entire pipeline code
- [SVG Viewer](https://marketplace.visualstudio.com/items?itemName=cssho.vscode-svgviewer) 
   As on the tin ;-)

**Comment by edmundmiller** [comment]
I guess the question is how nf-core/nextflow specific do we want to get? I vote we try to stay stay very opinionated on nextflow and nf-core related tools. So all of the ones so far I'm this thread fit that, but maybe something like format toggler (while very cool) isn't, or a code theme.

**Comment by edmundmiller** [comment]
https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case
https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker
https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory

I didn't know how opinionated we should get on git? I feel like it's an integral piece to the nf-core puzzle. I don't know if docker is necessary for everyone either.

Going to add a PR with the current stuff.

**Comment by ewels** [comment]
> I guess the question is how nf-core/nextflow specific do we want to get? I vote we try to stay stay very opinionated on nextflow and nf-core related tools. So all of the ones so far I'm this thread fit that, but maybe something like format toggler (while very cool) isn't, or a code theme.

I think opinionated is good, and that as long as we think a plugin is specifically useful for working with nf-core code, then it's valid. For example, I find Format toggler super useful for nf-core, as without it the auto-formatting breaks stuff in the nf-core/template files especially (eg. YAML files with Jinja variable placeholders).

Stuff like Docker could also be great to help people work with tools and the website, as well as building pipeline containers.

It could be nice to add some _"💡 Tip:"_ type things to the nf-core docs explaining that we recommend packages to help with this stuff..?

Will close this issue now as most are now included in #2. Let's try to keep suggestions as separate issues (or better still, PRs) to keep discussion easy to track 👍🏻
